# Generated by Django 3.1.4 on 2021-02-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20210201_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.userprofile'),
        ),
    ]
