# Generated by Django 3.1.4 on 2021-02-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_status_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.userprofile'),
        ),
    ]
