# Generated by Django 3.1.4 on 2021-02-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210202_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Procurement', 'Procurement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Official',
        ),
    ]
