# Generated by Django 3.1.4 on 2021-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20210203_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ethiopia'), (2, 'Sudan'), (3, 'South Sudan'), (4, 'Djibouti'), (5, 'Somalia')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Official'), (2, 'Finance'), (3, 'Procurement'), (4, 'IT'), (5, 'HR')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Procurement', 'Procurement'), ('IT', 'IT')], max_length=100),
        ),
    ]
