# Generated by Django 3.1.4 on 2021-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20210203_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('IT', 'IT'), ('Procurement', 'Procurement')], max_length=100),
        ),
    ]
