# Generated by Django 3.1.4 on 2021-02-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20210203_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Procurement', 'Procurement'), ('Finance', 'Finance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.official'),
        ),
    ]
