# Generated by Django 3.1.4 on 2021-02-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20210203_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Procurement', 'Procurement'), ('IT', 'IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.official'),
        ),
    ]
