# Generated by Django 3.1.4 on 2021-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20210203_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Procurement', 'Procurement'), ('IT', 'IT'), ('Finance', 'Finance')], max_length=100),
        ),
    ]
