# Generated by Django 3.1.4 on 2021-02-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20210204_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Procurement', 'Procurement'), ('IT', 'IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='official',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='organization',
            field=models.CharField(choices=[('LORC_SUD', 'LORC_SUD'), ('LORC_ETH', 'LORC_ETH')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Official',
        ),
    ]
